# this github action regenerates the next.js package for this site.

name: generate-static-files

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: npm install
        run: npm install

      - name: next build
        run: npm run build

      - name: next export
        run: npm run export

      - name: Commit content
        run: |
          git config --global user.name 'next.js'
          git config --global user.email 'mdlopresti@users.noreply.github.com'
          git add out/
          git commit -m "Updated static bundle"
          git push